name: Auto Merge

on:
  push:
    branches:
      - 'upload-*' # Giả sử các branch được tạo tự động có tiền tố là 'upload-'

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch tất cả lịch sử để có thể merge

      - name: Automatic Merge
        uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: "" # Không sử dụng label để trigger merge
          MERGE_METHOD: "merge" # Sử dụng phương thức merge
          MERGE_COMMIT_MESSAGE: "auto-merge: {{headBranch}}"
          MERGE_FORKS: false
          MERGE_RETRIES: 6
          MERGE_RETRY_SLEEP: 10000
          UPDATE_LABELS: ""
          UPDATE_METHOD: "merge"
